-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
-- 

-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicase_contactlock`;
DROP TABLE IF EXISTS `civicrm_case_category_instance`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_case_category_instance
-- *
-- * Stores Case Category Instance Details
-- *
-- *******************************************************/
CREATE TABLE `civicrm_case_category_instance` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique CaseCategoryInstance Id',
     `category_id` int unsigned NOT NULL   COMMENT 'One of the values of the case_type_categories option group',
     `instance_id` int unsigned NOT NULL   COMMENT 'One of the values of the case_category_instance_type option group',
     `singular_label` varchar(255) NOT NULL   COMMENT 'A singular noun for the case category instance' 
,
        PRIMARY KEY (`id`)
 
    ,     UNIQUE INDEX `unique_category`(
        category_id
  )
  
 
)    ;

-- /*******************************************************
-- *
-- * civicase_contactlock
-- *
-- * This table implements a list of contacts that have been locked out of specific cases, to which they will only have basic view access.
-- *
-- *******************************************************/
CREATE TABLE `civicase_contactlock` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique CaseContactLock ID',
     `case_id` int unsigned    COMMENT 'Case ID that is locked.',
     `contact_id` int unsigned    COMMENT 'Contact for which the case is locked.' 
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicase_contactlock_case_id FOREIGN KEY (`case_id`) REFERENCES `civicrm_case`(`id`) ON DELETE CASCADE,          CONSTRAINT FK_civicase_contactlock_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE  
)    ;

 